WIP: Implement build-iso
QubesOS/qubes-builderv2-github pull request #8
Opened 2023-03-05 17:14 UTC by fepitre

- Several fixes

2023-03-14 00:24 UTC, marmarek requested changes

2023-03-14 00:24 UTC, marmarek commented on github-action.py
> +class BaseAutoAction:
Why not ABC? If you don't need `upload` in ISO action, you can add dummy method (raising NotImplementedError) instead.

2023-03-14 00:24 UTC, marmarek commented on github-action.py
> +        self.config.set("iso", config_iso)
There should be also some way to set `is-final` (for example when building RC vs final release). I'm okay-ish with doing that implicitly based on the version (whether it contains rc/alpha/beta) - for example configurable list of strings to look in version to force is-final=false.

2023-03-14 00:24 UTC, marmarek commented on github-action.py
> +                if OpenQA_Client and OpenQAClientError:
This should be configurable, not only by the module presence.

2023-03-14 08:40 UTC, fepitre commented on github-action.py
> +class BaseAutoAction:
Yes I did at first, just wondering if ABC were really necessary but yes let's do this dummy method.

2023-03-15 12:49 UTC, marmarek requested changes

2023-03-15 12:49 UTC, marmarek commented on github-action.py
> +        is_final=False,
How `is_final` can be set? Currently only via a manual call, right?

2023-03-15 12:49 UTC, marmarek commented on github-action.py
> +        raise NotImplemented
```suggestion
        raise NotImplementedError
```
`NotImplemented` exists too, but is not an exception

2023-03-15 13:19 UTC, marmarek approved these changes

2023-03-16 01:26 UTC, merged